### PR TITLE
add a CI action with proxy services

### PR DESCRIPTION
**Pull request by robbkidd**
* adds a GitHub Actions workflow to run the tests with two live proxies (HTTP/s and SOCKS) for integration testing
* updates the tests:
  * use different target sites
  * check the new target content
  * skip the proxy integration tests if environment variables are not set
* includes the docker-compose config I used to test things locally and on which I set up the CI GitHub Action

This is not a very exciting PR without the workflow approved for running in this repo. Witness [the success over in my fork](https://github.com/robbkidd/superagent-proxy/pull/1/checks).

### CODE REVIEW

**Comment by TooTallNate** [comment]
Thanks! Seems like CI didn't kick off after merge though. Perhaps something isn't configured correctly in the workflow file?

**Comment by robbkidd** [comment]
> Perhaps something isn't configured correctly in the workflow file?

Perhaps! I'll look into it!

**Comment by robbkidd** [comment]
Except … it seems [it did run on the merged commit](https://github.com/TooTallNate/superagent-proxy/actions/runs/5744539999), GitHub's just not sprinkling the green check on the commit. 😕

**Comment by robbkidd** [comment]
Brain dumping how to use Docker for running tests locally in dev.

```shell
❯ docker-compose up --detach
❯ docker-compose exec test npm install
❯ docker-compose exec test npm test
# make modifications, repeat install and/or test as appropriate
# when done
❯ docker-compose down
```

I notice again that the project has a `yarn.lock`. Those commands could have `yarn` swapped out for `npm`. I could update the CI workflow to run yarn instead, if you would prefer, @TooTallNate.

**Pull request merged**
